"""
Django settings for clickserver project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r$m_w185is44+at6kx-ivh9ll!+9uy2_j9bdff%^bq*z_8hlhq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS =['3.6.225.178','almeapp.com','127.0.0.1','localhost']
CORS_ORIGIN_ALLOW_ALL = True
SECURE_SSL_REDIRECT = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events',
    'corsheaders',
    'rest_framework',
    'apiresult',
    'rest_framework.authtoken',
    'celery',
    'notification',
    'analytics',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    #'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clickserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clickserver.wsgi.application'
# use backend db for sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
        'default': {
            'ENGINE':'django.db.backends.mysql',
            #'OPTIONS':{
            #    'read_default_file':'/home/ubuntu/clickstream/auth/mysql.cnf'
            #},
            # 'NAME':'events',
            # 'USER':'root',
            # 'PASSWORD':'nexarc@123',
            # #ip address of the database
            # 'HOST':'localhost',
            # 'PORT':'3306',
            #TODO: Change back to original database after one time run
            'NAME':'events',
            'USER':'new_user',
            'PASSWORD':'Circuit@123',
            #ip address of the database
            'HOST':'3.6.225.178',
            'HOST':'localhost',
            'PORT':'3306',
            },
        }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s [%(filename)s:%(lineno)d] %(message)s',
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            #'filename': '/home/ubuntu/clickstream/django/clickserver/logs/info.log', #TODO: Change back to this log file
            'filename': '/Users/adityaganguli/Documents/Technew/clickstream-server/django/clickserver/logs/info.log',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'INFO',
    },
}




# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/home/ubuntu/clickstream/site/public/static'
MEDIA_ROOT = '/home/ubuntu/clickstream/site/public/media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

#CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_BEAT_SCHEDULE = {
    'update-every-minute': {
        'task': 'apiresult.tasks.update_database',
        'schedule': 120, # TODO: Change to 60 seconds
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtppro.zoho.in'  # Zoho's outgoing server name
EMAIL_PORT = 587  # You can also use 465
EMAIL_USE_TLS = True  # Set it to False if you want to use SSL
EMAIL_HOST_USER = 'aditya@almeapp.co'  # Your Zoho email
EMAIL_HOST_PASSWORD = 'Circuit@123'  # Your Zoho password



# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_REDIS = {
#     'host': 'localhost',
#     'port': 6379,
#     'db': 0,
#     'password': '',
#     'prefix': 'session',
#     'socket_timeout': 1,
#     'retry_on_timeout': False
# }
# SESSION_REDIS_ALIAS = "default"

# SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://localhost:6379/0',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }

TEST_RUNNER = 'apiresult.test_runner.NoDbTestRunner'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
