# Generated by Django 4.1.2 on 2022-11-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('session', models.TextField()),
                ('user_login', models.TextField()),
                ('user_id', models.TextField()),
                ('click_time', models.DateTimeField()),
                ('user_regd', models.TextField()),
                ('user_agent', models.TextField()),
                ('browser', models.TextField()),
                ('os', models.TextField()),
                ('event_type', models.TextField()),
                ('event_name', models.TextField()),
                ('source_url', models.TextField()),
            ],
            options={
                'db_table': 'event_raw',
            },
        ),
    ]
