# Generated by Django 4.1.2 on 2022-11-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='app_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
