# Generated by Django 4.1.2 on 2022-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='click_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
