# Generated by Django 4.1.2 on 2022-12-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_click_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='product_category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='product_created_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='product_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='product_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='product_price',
            field=models.TextField(null=True),
        ),
    ]
