# Generated by Django 4.1.2 on 2022-12-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_product_category_event_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='product_created_date',
            field=models.TextField(null=True),
        ),
    ]
