# Generated by Django 4.1.2 on 2023-02-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='click_text',
            field=models.TextField(default=''),
        ),
    ]
