# Generated by Django 4.1.2 on 2023-02-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('app_name', models.TextField(null=True)),
                ('tokens', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('categories', models.JSONField(null=True)),
                ('app_name', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user_login', models.TextField()),
                ('user_id', models.TextField()),
                ('app_name', models.TextField(null=True)),
                ('num_sessions', models.IntegerField()),
                ('last_visit', models.DateTimeField()),
                ('first_visit', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiresult.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiresult.user')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiresult.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiresult.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiresult.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiresult.user')),
            ],
        ),
    ]
